baseURL = 'https://wmjim.github.io'     # ç«™ç‚¹æ ¹ URL
languageCode = 'zh-cn'                  # è¯­è¨€ä»£ç ï¼ˆå½±å“ RSS ç­‰ï¼‰
title = "Mengw's Blog"                  # è®¾ç½®ç½‘ç«™ æ ‡é¢˜
theme = "PaperMod"                      # è®¾ç½®ç½‘ç«™ä¸»é¢˜
defaultContentLanguage = "zh"

# Hugo è¡Œä¸ºæ§åˆ¶
enableInlineShortcodes = true           # å…è®¸åœ¨è¡Œå†…ä½¿ç”¨çŸ­ä»£ç 
enableEmoji = true                      # æ”¯æŒ :smile: ç­‰ emoji ç®€å†™
enableRobotsTXT = true                  # è‡ªåŠ¨ç”Ÿæˆ robots.txt
hasCJKLanguage = true                   # å¯ç”¨ä¸­æ–‡/æ—¥æ–‡/éŸ©æ–‡æ–­è¯ä¼˜åŒ–
# æ·»åŠ è¿™è¡Œæ¥ç¦ç”¨ Google Analytics
[services.googleAnalytics]
    ID = ""  # è®¾ç½®ä¸ºç©ºå­—ç¬¦ä¸²ï¼Œæˆ–è€…ä½ çš„ GA ID


# æ„å»ºé€‰é¡¹
buildDrafts = false     # ä¸æ„å»ºè‰ç¨¿
buildFuture = false     # ä¸æ„å»ºæœªæ¥æ—¥æœŸæ–‡ç« 
buildExpired = false    # ä¸æ„å»ºå·²è¿‡æœŸæ–‡ç« 

StartYear = 2024
EndYear = 2025
# PaperMod ä¼šè‡ªåŠ¨æ˜¾ç¤ºä¸º "Â© 2024â€“2025"



# åˆ†é¡µä¸æ‘˜è¦
[pagination]
    pagerSize = 15      # é¦–é¡µæ¯é¡µæ˜¾ç¤º 15 ç¯‡æ–‡ç« 
    summaryLength = 140     # æ‘˜è¦é•¿åº¦ï¼ˆä¸­æ–‡å­—ç¬¦ï¼‰

# URL ä¸æ°¸ä¹…é“¾æ¥
[permalinks]
    post = "/:title/"     # æ–‡ç«  URL æ ¼å¼ä¸º /æ–‡ç« æ ‡é¢˜/

    # ä¸»èœå•
[menu]
    [[menu.main]]
        identifier = "home"
        name = "ğŸ  ä¸»é¡µ"
        url = "/"
        weight = 1

    [[menu.main]]
        identifier = "posts"
        name = "ğŸ“š æ–‡ç« "
        url = "/posts/"
        weight = 2

    [[menu.main]]
        name = "â± æ—¶é—´è½´"
        url = "/archives/"
        weight = 3

    [[menu.main]]
        identifier = "tags"
        name = "ğŸ”– æ ‡ç­¾"
        url = "/tags/"
        weight = 4

    [[menu.main]]
        identifier = "categories"
        name = "ğŸ“ åˆ†ç±»"
        url = "/categories/"
        weight = 5

    [[menu.main]]
        identifier = "search"
        name = "ğŸ” æœç´¢"
        url = "/search/"
        weight = 6

    [[menu.main]]
        identifier = "about"
        name = "ğŸ‘¤ å…³äº"
        url = "/about/"
        weight = 7



[params]
    env = "production"
    author = "mengw"
    description = "ä¸ªäººåšå®¢ï¼Œè®°å½•å’Œåˆ†äº«"
    defaultTheme = "auto"
    ShowCodeCopyButtons = true      # ä»£ç å—æ˜¾ç¤ºå¤åˆ¶æŒ‰é’®
    ShowReadingTime = true          # æ˜¾ç¤ºé˜…è¯»æ—¶é•¿
    ShowPostNavLinks = true         # æ˜¾ç¤ºä¸Š/ä¸‹ä¸€ç¯‡æ–‡ç« 
    ShowBreadCrumbs = true          # æ˜¾ç¤ºé¢åŒ…å±‘å¯¼èˆª
    ShowWordCounts = true           # æ˜¾ç¤ºå­—æ•°ç»Ÿè®¡
    ShowLastMod = true              # æ˜¾ç¤ºæœ€åä¿®æ”¹æ—¶é—´
    ShowToc = true                  # æ˜¾ç¤ºç›®å½•
    TocOpen = true                  # ç›®å½•é»˜è®¤å±•å¼€ï¼‰
    # enableMath = true               # æ‰€æœ‰é¡µé¢å¯ç”¨ LaTex
    enableSearch = true
    # ä¸ªäººå¡ç‰‡é¡µ
    [params.profileMode]
        enabled = true
        title = "mengw"                    # å¯é€‰ï¼Œé»˜è®¤ä½¿ç”¨ site.title
        subtitle = "Software Engineer & Open Source Enthusiast"
        imageUrl = "/images/avatar.jpg"     # å¯é€‰ï¼šå¤´åƒ URL
        imageTitle = "God Bless YouğŸ‘‹"            # å¯é€‰ï¼šalt æ–‡æœ¬
        imageWidth = 120                                # å•ä½ï¼špx
        imageHeight = 120
    [profileMode.buttons]
        Archive = "/archive"
        GitHub = "https://github.com/wmjim"
        Blog = "/posts"
    # ç½‘ç«™æ ‡è¯†ï¼ˆå·¦ä¸Šè§’ï¼‰
    [params.label]
        text = "Mengw's Blog"
        icon = "/images/avatar.jpg"
        iconHeight = 35
    [params.assets]
        disableScrollToTop = false # åŒæ—¶æ˜¾ç¤ºå›åˆ°é¡¶éƒ¨æŒ‰é’®
        favicon = "/images/avatar.jpg"
    [params.cover]
        hidden = false         # ä¸éšè—å°é¢
        hiddenInList = false   # åˆ—è¡¨é¡µæ˜¾ç¤ºå°é¢
        hiddenInSingle = true  # å•ç¯‡æ–‡ç« é¡µéšè—å°é¢ï¼ˆä½ è®¾ä¸º trueï¼‰
    # é…ç½® Fuse.js æœç´¢é€‰é¡¹
    [params.fuseOpts]
        isCaseSensitive = false # æ˜¯å¦åŒºåˆ†å¤§å°å†™
        shouldSort = true       # æ˜¯å¦æ ¹æ®åŒ¹é…åº¦å¯¹ç»“æœæ’åº
        location = 0            # å¼€å§‹åŒ¹é…çš„æ–‡æœ¬ä½ç½®
        distance = 1000
        threshold = 0.4
        minMatchCharLength = 0
        # limit = 10  # å–æ¶ˆæ³¨é‡Šå¯é™åˆ¶æœç´¢ç»“æœæ•°é‡
        # æŒ‡å®šåœ¨å“ªäº›å­—æ®µä¸­æœç´¢ï¼Œtitle:æ–‡ç« æ ‡é¢˜ã€permalink:æ–‡ç« urlã€summaryï¼šæ‘˜è¦ã€content:å…¨æ–‡å†…å®¹
        keys = ["title", "permalink", "summary", "content"]
        # å¼€å¯åŠŸèƒ½
    # ç¼–è¾‘æ­¤é¡µ
    [params.editPost]
        URL = "https://github.com/wmjim/wmjim.github.io/edit/main/content"
        Text = "ç¼–è¾‘æ­¤é¡µ"
        appendFilePath = true
    # æ·»åŠ  giscus è¯„è®ºç³»ç»Ÿ
    [params.giscus]
        enable = true  # æ·»åŠ è¿™ä¸ªå¼€å…³


# ç¤¾äº¤é“¾æ¥ - ä½¿ç”¨æ•°ç»„æ ¼å¼
[[params.socialIcons]]
    name = "github"
    url = "https://github.com/wmjim"
[[params.socialIcons]]
    name = "email"
    url = "meng.w1016@outlook.com"
[[params.socialIcons]]
    name = "medium"
    url = "https://medium.com/@meng.w1016"
[[params.socialIcons]]
    name = "twitter"
    url = "yourhandle"
[[params.socialIcons]]
    name = "bilibili"
    url = "https://space.bilibili.com/3546830520454041"
# æŒ‰é’®åˆ—è¡¨
[[params.profileMode.buttons]]
    name = "Archive"
    url = "/archive"

[[params.profileMode.buttons]]
    name = "GitHub"
    url = "https://github.com/alexchen"

[[params.profileMode.buttons]]
    name = "Blog"
    url = "/posts"


[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true # å…è®¸åœ¨ MarkDown ä¸­ä½¿ç”¨åŸå§‹ HTML
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 6
        ordered = false
    # ä»£ç é«˜äº®
    [markup.highlight]
        codeFences = true       # å¯ç”¨å›´æ ä»£ç å—
        guessSyntax = false     # å…³é—­è‡ªåŠ¨çŒœä»£ç è¯­è¨€
        # lineNos = true          # æ˜¾ç¤ºè¡Œå·
        lineNumbersInTable = true
        noClasses = true
        style = "dracula"  # å¯é€‰ monokaiã€github ç­‰

# åˆ†ç±»æ³•
[taxonomies]
    tag = "tags"                # æ ‡ç­¾åˆ†ç±»
    category = "categories"     # åˆ†ç±»
    series = "series"           # ç³»åˆ—åˆ†ç±»

# è‡ªå®šä¹‰é¦–é¡µè¾“å‡ºæ ¼å¼
[outputs]
    home = ["HTML", "RSS", "JSON"]
    section = ['HTML', 'RSS']
    taxonomy = ['HTML']
    term = ['HTML']

[services]
    [services.rss]
        limit = 42

# RSS è®¢é˜…
[outputFormats]
    [outputFormats.RSS]
        mediatype = "application/rss+xml"
        baseName = "feed"
